# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_comboboxForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbSehirler = QtWidgets.QComboBox(self.centralwidget)
        self.cbSehirler.setGeometry(QtCore.QRect(40, 20, 171, 61))
        self.cbSehirler.setObjectName("cbSehirler")
        self.BtnGetItem = QtWidgets.QPushButton(self.centralwidget)
        self.BtnGetItem.setGeometry(QtCore.QRect(40, 120, 121, 41))
        self.BtnGetItem.setObjectName("BtnGetItem")
        self.BtnLoadItems = QtWidgets.QPushButton(self.centralwidget)
        self.BtnLoadItems.setGeometry(QtCore.QRect(210, 120, 131, 41))
        self.BtnLoadItems.setObjectName("BtnLoadItems")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(270, 20, 131, 51))
        self.lblResult.setObjectName("lblResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnGetItem.setText(_translate("MainWindow", "Get Item"))
        self.BtnLoadItems.setText(_translate("MainWindow", "Load Items"))
        self.lblResult.setText(_translate("MainWindow", "TextLabel"))
